#define	BINTREE <bintree.h>
#define	BITMAP <bitmap.h>
#define	CUSTOMOPS <customops.h>
#define	DEVICE <device.h>
#define	DEVCREATE <devcreate.h>
#define	DEVICETYPES <devicetypes.h>
#define	DEVIMAGE <devimage.h>
#define DEVMARK <devmark.h>
#define	DEVPATTERN <devpattern.h>
#define	ENVIRONMENT <environment.h>
#define	EXCEPT <except.h>
#define FILESYSTEM <filesystem.h>
#define FILETYPES <filetypes.h>
#define	FOREGROUND <foreground.h>
#define	FP <fp.h>
#define	POSTSCRIPT <postscript.h>
#define	PSLIB <pslib.h>
#define	PUBLICTYPES <publictypes.h>
#define STREAM <stream.h>
#define UNIXSTREAM <unixstream.h>
